package enums;

public enum SpeciesName {
    CHARIGATOR,
    FIRE_GOBLIN,
    FLAME_CAT,
    KATANA_MONKEY,
    KILLER_ROOSTER,
    MONK,
    KRAKEN_MAN,
    FISH_MAN,
    FIREFIGHTER,
    DOBI,
    RAINBOWCORN,
    WIZARD,
    BAZOOKA_GORILLA,
    CRAZY_SLOTH,
    MUD_MONSTER
}
